----------------------ADDRESES------------------------
insert into address (city, country, latitude, longitude, number, street) values ('Timaru', 'New Zealand', 73.09, 2.71, '3', 'Truax');
insert into address (city, country, latitude, longitude, number, street) values ('Tūkrah', 'Libya', 11.73, 63.94, '497', 'Sunfield');
insert into address (city, country, latitude, longitude, number, street) values ('Vårby', 'Sweden', 18.53, 40.48, '1051', 'Carberry');
insert into address (city, country, latitude, longitude, number, street) values ('Huyuan', 'China', 9.89, 45.04, '2680', 'Fulton');
insert into address (city, country, latitude, longitude, number, street) values ('Hidalgo', 'Mexico', 85.21, 28.72, '633', 'School');
insert into address (city, country, latitude, longitude, number, street) values ('Wonokerso', 'Indonesia', 60.63, 43.72, '1', 'Rockefeller');
insert into address (city, country, latitude, longitude, number, street) values ('Rozwadza', 'Poland', 91.23, 48.92, '110', 'Upham');
insert into address (city, country, latitude, longitude, number, street) values ('Kayes', 'Republic of the Congo', 8.3, 24.5, '90', 'Loomis');
insert into address (city, country, latitude, longitude, number, street) values ('Skänninge', 'Sweden', 8.49, 81.93, '821', 'Center');
insert into address (city, country, latitude, longitude, number, street) values ('Wudan', 'China', 57.84, 50.12, '59721', 'Amoth');
insert into address (city, country, latitude, longitude, number, street) values ('Ålesund', 'Norway', 4.23, 84.8, '1544', 'Maryland');
insert into address (city, country, latitude, longitude, number, street) values ('Kukulu', 'Indonesia', 88.29, 36.06, '536', 'Loftsgordon');
insert into address (city, country, latitude, longitude, number, street) values ('Akademgorodok', 'Russia', 5.83, 59.42, '3076', 'Algoma');
insert into address (city, country, latitude, longitude, number, street) values ('Kotkot', 'Philippines', 85.74, 3.21, '4459', 'Badeau');
insert into address (city, country, latitude, longitude, number, street) values ('Borås', 'Sweden', 32.93, 97.14, '15248', 'Golden Leaf');
insert into address (city, country, latitude, longitude, number, street) values ('Luozhuang', 'China', 63.4, 66.64, '28148', 'Graceland');
insert into address (city, country, latitude, longitude, number, street) values ('Umag', 'Croatia', 35.15, 49.31, '968', 'Declaration');
insert into address (city, country, latitude, longitude, number, street) values ('Kruševac', 'Serbia', 97.25, 89.47, '21576', 'Fieldstone');
insert into address (city, country, latitude, longitude, number, street) values ('Baykonyr', 'Kazakhstan', 59.99, 48.9, '02', 'Harper');
insert into address (city, country, latitude, longitude, number, street) values ('Fulu', 'China', 78.36, 48.14, '25213', 'Sage');
insert into address (city, country, latitude, longitude, number, street) values ('Kashihara-shi', 'Japan', 74.21, 37.04, '142', 'Reindahl');
insert into address (city, country, latitude, longitude, number, street) values ('Louisville', 'United States', 8.91, 26.45, '08', 'Delaware');
insert into address (city, country, latitude, longitude, number, street) values ('Kalpin', 'China', 54.24, 90.38, '4', 'Buell');
insert into address (city, country, latitude, longitude, number, street) values ('Shanmu', 'China', 4.08, 91.91, '6', 'La Follette');
insert into address (city, country, latitude, longitude, number, street) values ('Śmiłowo', 'Poland', 53.53, 18.45, '73584', 'Mifflin');
insert into address (city, country, latitude, longitude, number, street) values ('Cran-Gevrier', 'France', 52.3, 1.24, '58315', 'Eliot');
insert into address (city, country, latitude, longitude, number, street) values ('Chenzhou', 'China', 58.37, 60.58, '7528', 'Lakewood');
insert into address (city, country, latitude, longitude, number, street) values ('Pahing Jalatrang', 'Indonesia', 81.22, 89.36, '0181', 'Bashford');
insert into address (city, country, latitude, longitude, number, street) values ('A-da-Gorda', 'Portugal', 70.86, 47.96, '6859', 'Cottonwood');
insert into address (city, country, latitude, longitude, number, street) values ('Guixi', 'China', 59.04, 42.63, '4959', 'Graceland');
insert into address (city, country, latitude, longitude, number, street) values ('Tertek', 'Indonesia', 58.14, 85.51, '9', 'Granby');
insert into address (city, country, latitude, longitude, number, street) values ('Irupi', 'Brazil', 91.85, 30.77, '621', 'Vermont');
insert into address (city, country, latitude, longitude, number, street) values ('Anding', 'China', 1.69, 96.27, '8', 'Stang');
insert into address (city, country, latitude, longitude, number, street) values ('Chimtāl', 'Afghanistan', 96.09, 81.85, '800', 'Sutherland');
insert into address (city, country, latitude, longitude, number, street) values ('Yongshan', 'China', 15.44, 57.36, '68237', '3rd');
insert into address (city, country, latitude, longitude, number, street) values ('Binawara', 'Indonesia', 12.69, 7.57, '224', 'Haas');
insert into address (city, country, latitude, longitude, number, street) values ('Mirovka', 'Ukraine', 21.05, 81.67, '39689', 'Di Loreto');
insert into address (city, country, latitude, longitude, number, street) values ('Yangqing', 'China', 18.7, 72.77, '32', 'Bellgrove');
insert into address (city, country, latitude, longitude, number, street) values ('Cha’anpu', 'China', 97.59, 93.21, '68', 'Mcbride');
insert into address (city, country, latitude, longitude, number, street) values ('Umeå', 'Sweden', 44.75, 11.33, '815', 'Buena Vista');
insert into address (city, country, latitude, longitude, number, street) values ('Lalapanzi', 'Zimbabwe', 28.5, 19.97, '885', 'Dottie');
insert into address (city, country, latitude, longitude, number, street) values ('Jacarezinho', 'Brazil', 19.66, 9.94, '2', 'Donald');
insert into address (city, country, latitude, longitude, number, street) values ('Guozhai', 'China', 83.9, 86.69, '123', 'Marcy');
insert into address (city, country, latitude, longitude, number, street) values ('Chvaletice', 'Czech Republic', 17.23, 7.29, '8533', 'Eastwood');
insert into address (city, country, latitude, longitude, number, street) values ('Koanara', 'Indonesia', 24.24, 88.9, '79188', 'Hermina');
insert into address (city, country, latitude, longitude, number, street) values ('Roma', 'Italy', 91.3, 65.54, '416', 'Utah');
insert into address (city, country, latitude, longitude, number, street) values ('Saint-Priest', 'France', 89.88, 44.34, '9928', 'Old Shore');
insert into address (city, country, latitude, longitude, number, street) values ('Pensacola', 'United States', 8.41, 25.49, '4764', 'Kinsman');
insert into address (city, country, latitude, longitude, number, street) values ('Gävle', 'Sweden', 71.73, 88.66, '243', 'Northridge');
insert into address (city, country, latitude, longitude, number, street) values ('Haoshui', 'China', 23.94, 40.47, '34880', 'Lyons');
insert into address (city, country, latitude, longitude, number, street) values ('Cikujang', 'Indonesia', 72.86, 4.43, '8829', 'Starling');
insert into address (city, country, latitude, longitude, number, street) values ('Yeniköy', 'Turkey', 60.79, 16.46, '79159', 'Nova');
insert into address (city, country, latitude, longitude, number, street) values ('Toila', 'Estonia', 83.07, 8.85, '8', 'Toban');
insert into address (city, country, latitude, longitude, number, street) values ('Värnamo', 'Sweden', 7.99, 82.75, '11', 'Bultman');
insert into address (city, country, latitude, longitude, number, street) values ('Zhaitou', 'China', 86.97, 42.97, '9273', 'Emmet');
insert into address (city, country, latitude, longitude, number, street) values ('Ushumun', 'Russia', 22.01, 61.58, '4702', 'Commercial');
insert into address (city, country, latitude, longitude, number, street) values ('Pregrada', 'Croatia', 0.76, 51.08, '0', 'Carioca');
insert into address (city, country, latitude, longitude, number, street) values ('Nyanza', 'Rwanda', 34.19, 42.55, '95', 'Thackeray');
insert into address (city, country, latitude, longitude, number, street) values ('Randegan', 'Indonesia', 52.59, 48.66, '0', 'Gina');
insert into address (city, country, latitude, longitude, number, street) values ('Tampa', 'United States', 9.11, 8.7, '6738', 'Merchant');
insert into address (city, country, latitude, longitude, number, street) values ('Sanjinquan', 'China', 71.26, 36.29, '1684', 'Spenser');
insert into address (city, country, latitude, longitude, number, street) values ('Baojia', 'China', 13.5, 20.0, '0', 'Farwell');
insert into address (city, country, latitude, longitude, number, street) values ('Maguling', 'Philippines', 59.48, 40.27, '06', 'Dorton');
insert into address (city, country, latitude, longitude, number, street) values ('Bemposta', 'Portugal', 39.6, 31.98, '36', 'Porter');
insert into address (city, country, latitude, longitude, number, street) values ('Asaka', 'Japan', 30.68, 97.19, '62', 'Westport');
insert into address (city, country, latitude, longitude, number, street) values ('Mosquera', 'Colombia', 12.18, 94.33, '5', 'Goodland');
insert into address (city, country, latitude, longitude, number, street) values ('Xintaimen', 'China', 61.3, 62.11, '894', 'Stone Corner');
insert into address (city, country, latitude, longitude, number, street) values ('Niños Heroes', 'Mexico', 23.38, 32.13, '895', 'Cardinal');
insert into address (city, country, latitude, longitude, number, street) values ('Igbaras', 'Philippines', 72.79, 84.43, '32', 'West');
insert into address (city, country, latitude, longitude, number, street) values ('Cikujang', 'Russia', 31.29, 34.43, '323', 'Dorton');

----------------------PERSONS------------------------
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('A-', '1999-07-07 09:47:39', 'mbullar0@businessweek.com', 'Male', 'Ftn', 7808765978633, 'Meryl', 'occupation', '123', '4634368672', 0, 'Bullar', 1);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('A+', '1965-01-22 04:53:26', 'ccrankshaw1@cnn.com', 'Female', 'Ftn', 7345245868286, 'Caresa', 'occupation', '123', '6686071149', 0, 'Crankshaw', 2);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('B+', '1966-06-29 10:21:58', 'ehuband2@toplist.cz', 'Female', 'Ftn', 9162644144769, 'Elfie', 'occupation', '123', '9511617702', 0, 'Huband', 3);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('B-', '1994-09-06 14:11:50', 'rmacphail3@dagondesign.com', 'Male', 'Ftn', 2301779240026, 'Rowan', 'occupation', '123', '4446346662', 0, 'MacPhail', 4);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('O+', '1962-12-17 03:30:57', 'rgarmston4@webs.com', 'Male', 'Ftn', 9149543019003, 'Ricard', 'occupation', '123', '1827487358', 0, 'Garmston', 5);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('O-', '1994-09-20 18:59:22', 'griggulsford5@gov.uk', 'Female', 'Ftn', 5226170294254, 'Gwenora', 'occupation', '123', '4024070105', 0, 'Riggulsford', 6);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('A+', '1998-01-19 18:48:18', 'cnann6@cyberchimps.com', 'Female', 'Ftn', 9686637619064, 'Celina', 'occupation', '123', '3254482010', 0, 'Nann', 7);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('AB-', '1978-04-14 17:14:48', 'ngonoude7@bloglovin.com', 'Genderfluid', 'Ftn', 1717502657087, 'Ninetta', 'occupation', '123', '2513364498', 0, 'Gonoude', 8);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('B-', '1969-09-25 19:00:58', 'cshearston8@devhub.com', 'Male', 'Ftn', 9629156671107, 'Cole', 'occupation', '123', '9804316604', 0, 'Shearston', 9);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('A-', '1995-06-04 04:46:16', 'achristophle9@taobao.com', 'Female', 'Ftn', 2125560091079, 'Arlie', 'occupation', '123', '4012141978', 0, 'Christophle', 10);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('AB+', '1996-07-28 22:00:48', 'aprandoa@salon.com', 'Male', 'Ftn', 6645562584576, 'Armand', 'occupation', '123', '4858953772', 0, 'Prando', 11);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('B-', '2000-07-17 17:00:54', 'kandrinib@google.cn', 'Female', 'Ftn', 5552152272803, 'Kata', 'occupation', '123', '9074903021', 0, 'Andrini', 12);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('O+', '1988-02-21 17:25:57', 'fcrudgintonc@lulu.com', 'Female', 'Ftn', 7560941752253, 'Fancy', 'occupation', '123', '7733016000', 0, 'Crudginton', 13);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('O+', '1971-09-23 15:56:11', 'sborrettd@un.org', 'Male', 'Ftn', 7354609305351, 'Spenser', 'occupation', '123', '3472023779', 0, 'Borrett', 14);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('B+', '1999-05-26 15:58:31', 'gdoileye@wikispaces.com', 'Male', 'Ftn', 3931853013688, 'Gan', 'occupation', '123', '3271445740', 0, 'Doiley', 15);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('A+', '1968-06-22 18:26:21', 'cpumphreyf@google.es', 'Female', 'Ftn', 8396500947001, 'Ceil', 'occupation', '123', '6533689898', 0, 'Pumphrey', 16);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('AB-', '1964-10-24 15:41:50', 'dscudamoreg@a8.net', 'Non-binary', 'Ftn', 2943736182440, 'Dwayne', 'occupation', '123', '6582173878', 0, 'Scudamore', 17);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('A+', '1998-11-10 21:29:52', 'mbrookerh@taobao.com', 'Male', 'Ftn', 1187644341712, 'Massimiliano', 'occupation', '123', '6838784943', 0, 'Brooker', 18);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('B+', '1986-11-21 11:29:58', 'jsammuti@dot.gov', 'Male', 'Ftn', 9596780859464, 'Justis', 'occupation', '123', '4869684991', 0, 'Sammut', 19);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('AB+', '1976-01-23 21:46:54', 'bodamsj@rediff.com', 'Female', 'Ftn', 3377543148634, 'Bernetta', 'occupation', '123', '4302404397', 0, 'Odams', 20);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('A-', '1967-11-15 06:37:05', 'tsykesk@yandex.ru', 'Male', 'Ftn', 6550545215207, 'Teodoro', 'occupation', '123', '4145969369', 0, 'Sykes', 21);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('O-', '1986-10-30 05:28:33', 'lpithcockl@ucla.edu', 'Female', 'Ftn', 4110845347026, 'Louella', 'occupation', '123', '3381110138', 0, 'Pithcock', 22);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('A+', '1983-02-20 11:50:11', 'jboshardm@ustream.tv', 'Male', 'Ftn', 8705172546576, 'Johny', 'occupation', '123', '2553040558', 0, 'Boshard', 23);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('O-', '1994-09-14 17:24:11', 'vrappern@pen.io', 'Female', 'Ftn', 3336599742074, 'Valma', 'occupation', '123', '1751050910', 0, 'Rapper', 24);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('A+', '1984-10-31 11:57:47', 'dlinfooto@soundcloud.com', 'Female', 'Ftn', 8854703305662, 'Darla', 'occupation', '123', '1733149177', 0, 'Linfoot', 25);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('AB-', '2002-04-29 01:55:10', 'vblankmanp@ifeng.com', 'Female', 'Ftn', 1989460435100, 'Vitoria', 'occupation', '123', '9728950002', 0, 'Blankman', 26);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('B-', '1965-07-19 00:18:55', 'fleethamq@stanford.edu', 'Genderfluid', 'Ftn', 1481982988528, 'Freddy', 'occupation', '123', '7267762959', 0, 'Leetham', 27);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('AB+', '1976-08-31 18:08:55', 'imakeyr@businessweek.com', 'Female', 'Ftn', 1714454250231, 'Irena', 'occupation', '123', '6642456320', 0, 'Makey', 28);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('O+', '1983-11-13 21:28:42', 'lclines@sciencedaily.com', 'Agender', 'Ftn', 3365161982294, 'Leann', 'occupation', '123', '6511304563', 0, 'Cline', 29);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('A-', '1975-08-13 06:03:15', 'efrewert@blogs.com', 'Female', 'Ftn', 8497232274876, 'Elspeth', 'occupation', '123', '3812338291', 0, 'Frewer', 30);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('A+', '1969-10-23 19:50:25', 'tpenkeu@aboutads.info', 'Female', 'Ftn', 2517972528691, 'Tammie', 'occupation', '123', '2507182115', 0, 'Penke', 31);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('AB-', '1978-08-21 05:27:05', 'vseveryv@theglobeandmail.com', 'Female', 'Ftn', 1440062084088, 'Vinni', 'occupation', '123', '6373372334', 0, 'Severy', 32);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('B-', '1973-01-18 02:10:40', 'elomaxw@army.mil', 'Female', 'Ftn', 7658160221458, 'Estel', 'occupation', '123', '2408014837', 0, 'Lomax', 33);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('AB+', '1989-06-28 07:20:28', 'ftightx@ucsd.edu', 'Male', 'Ftn', 8732267318728, 'Franciskus', 'occupation', '123', '2996053662', 0, 'Tight', 34);
insert into person (blood_type, date_of_birth, email, gender, information_about_company, jmbg, name, occupation, password, phon_number, role, surname, address_id) values ('O+', '1998-10-05 05:01:39', 'bfoskeny@earthlink.net', 'Female', 'Ftn', 3064402491074, 'Bendite', 'occupation', '123', '3361586655', 0, 'Fosken', 35);

----------------------REGISTERED_USERS------------------------
insert into registered_user(deleted, person_id) values (false, 1);
insert into registered_user(deleted, person_id) values (false, 2);
insert into registered_user(deleted, person_id) values (false, 3);
insert into registered_user(deleted, person_id) values (false, 4);
insert into registered_user(deleted, person_id) values (false, 5);
insert into registered_user(deleted, person_id) values (false, 6);
insert into registered_user(deleted, person_id) values (false, 7);
insert into registered_user(deleted, person_id) values (false, 8);
insert into registered_user(deleted, person_id) values (false, 9);
insert into registered_user(deleted, person_id) values (false, 10);
insert into registered_user(deleted, person_id) values (false, 11);
insert into registered_user(deleted, person_id) values (false, 12);
insert into registered_user(deleted, person_id) values (false, 13);
insert into registered_user(deleted, person_id) values (false, 14);
insert into registered_user(deleted, person_id) values (false, 15);
insert into registered_user(deleted, person_id) values (false, 16);
insert into registered_user(deleted, person_id) values (false, 17);
insert into registered_user(deleted, person_id) values (false, 18);
insert into registered_user(deleted, person_id) values (false, 19);
insert into registered_user(deleted, person_id) values (false, 20);
insert into registered_user(deleted, person_id) values (false, 21);
insert into registered_user(deleted, person_id) values (false, 22);
insert into registered_user(deleted, person_id) values (false, 23);
insert into registered_user(deleted, person_id) values (false, 24);

----------------------QUESTION------------------------
insert into question (question, exact_value) values ('Da li imate vise od 50 kg', true);
insert into question (question, exact_value) values ('Da li imate simptome prehlade ili neke bolesti', false);
insert into question (question, exact_value) values ('Da li imate promene na kozi (osip, infekcije)', false);
insert into question (question, exact_value) values ('Da li imate suvise visok ili suvise nizak pritisak', false);
insert into question (question, exact_value) values ('Da li ste pod terapijom  vise ili nije proslo najmanje 7 dana od terapije antibiotika', false);
insert into question (question, exact_value) values ('Da li proslo vise od 6 meseci od probadanja tela i koze (pirsing), tetoviranja ili transfuzije krvi', true);
insert into question (question, exact_value) values ('Da li proslo manje od  7 dana od vadjenja zuba i manjih stomatoloskih intervencija', false);

----------------------CENTER------------------------
insert into center (average_rating, deleted, description, name, address_id) values (1.58, false, 'Vivamus tortor.', 'Wikibox', 36);
insert into center (average_rating, deleted, description, name, address_id) values (6.26, false, 'In eleifend quam a odio.', 'Thoughtstorm', 37);
insert into center (average_rating, deleted, description, name, address_id) values (2.89, false, 'Vestibulum rutrum rutrum neque.', 'Gabcube', 38);
insert into center (average_rating, deleted, description, name, address_id) values (9.69, false, 'Sed vel enim sit amet nunc viverra dapibus.', 'InnoZ', 39);
insert into center (average_rating, deleted, description, name, address_id) values (2.38, false, 'In sagittis dui vel nisl.', 'Rhyloo', 40);
insert into center (average_rating, deleted, description, name, address_id) values (1.9, false, 'Mauris lacinia sapien quis libero.', 'Pixoboo', 41);
insert into center (average_rating, deleted, description, name, address_id) values (2.67, false, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'Vimbo', 42);
insert into center (average_rating, deleted, description, name, address_id) values (3.5, false, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Eayo', 43);
insert into center (average_rating, deleted, description, name, address_id) values (7.74, false, 'Cras non velit nec nisi vulputate nonummy.', 'Thoughtstorm', 44);
insert into center (average_rating, deleted, description, name, address_id) values (8.64, false, 'Fusce posuere felis sed lacus.', 'Flashdog', 45);
insert into center (average_rating, deleted, description, name, address_id) values (1.15, false, 'Cras non velit nec nisi vulputate nonummy.', 'Trilith', 46);
insert into center (average_rating, deleted, description, name, address_id) values (9.64, false, 'Suspendisse ornare consequat lectus.', 'Oozz', 47);
insert into center (average_rating, deleted, description, name, address_id) values (1.37, false, 'Aenean sit amet justo.', 'Trunyx', 48);
insert into center (average_rating, deleted, description, name, address_id) values (8.29, false, 'Vivamus in felis eu sapien cursus vestibulum.', 'Skippad', 49);
insert into center (average_rating, deleted, description, name, address_id) values (7.52, false, 'Etiam pretium iaculis justo.', 'Ntags', 50);
insert into center (average_rating, deleted, description, name, address_id) values (2.6, false, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Browsebug', 51);
insert into center (average_rating, deleted, description, name, address_id) values (8.32, false, 'Praesent blandit.', 'Quatz', 52);
insert into center (average_rating, deleted, description, name, address_id) values (8.86, false, 'Nulla facilisi.', 'Yakitri', 53);
insert into center (average_rating, deleted, description, name, address_id) values (8.08, false, 'Duis ac nibh.', 'Devcast', 54);
insert into center (average_rating, deleted, description, name, address_id) values (8.04, false, 'Etiam faucibus cursus urna.', 'Avamba', 55);
insert into center (average_rating, deleted, description, name, address_id) values (3.29, false, 'Duis consequat dui nec nisi volutpat eleifend.', 'Dynabox', 56);
insert into center (average_rating, deleted, description, name, address_id) values (2.87, false, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Trudoo', 57);
insert into center (average_rating, deleted, description, name, address_id) values (2.09, false, 'Morbi vel lectus in quam fringilla rhoncus.', 'Thoughtbeat', 58);
insert into center (average_rating, deleted, description, name, address_id) values (3.96, false, 'Duis at velit eu est congue elementum.', 'Oyondu', 59);
insert into center (average_rating, deleted, description, name, address_id) values (8.6, false, 'Suspendisse potenti.', 'Brightbean', 60);
insert into center (average_rating, deleted, description, name, address_id) values (7.83, false, 'Proin eu mi.', 'Rhybox', 61);
insert into center (average_rating, deleted, description, name, address_id) values (6.86, false, 'Morbi quis tortor id nulla ultrices aliquet.', 'Quire', 62);
insert into center (average_rating, deleted, description, name, address_id) values (6.08, false, 'Proin eu mi.', 'Twitternation', 63);
insert into center (average_rating, deleted, description, name, address_id) values (1.48, false, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Janyx', 64);
insert into center (average_rating, deleted, description, name, address_id) values (9.88, false, 'Morbi vel lectus in quam fringilla rhoncus.', 'Blogtags', 65);
insert into center (average_rating, deleted, description, name, address_id) values (3.15, false, 'Pellentesque at nulla.', 'Lazzy', 66);
insert into center (average_rating, deleted, description, name, address_id) values (9.9, false, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Rhybox', 67);
insert into center (average_rating, deleted, description, name, address_id) values (6.9, false, 'Integer a nibh.', 'Eimbee', 68);
insert into center (average_rating, deleted, description, name, address_id) values (4.85, false, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Digitube', 69);
insert into center (average_rating, deleted, description, name, address_id) values (3.61, false, 'Mauris sit amet eros.', 'Oyoloo', 70);

----------------------CENTER_ADMINISTRATOR------------------------
insert into administrator_center(deleted, center_id, person_id) values (false, 1, 25);
insert into administrator_center(deleted, center_id, person_id) values (false, 1, 26);
insert into administrator_center(deleted, center_id, person_id) values (false, 2, 27);
insert into administrator_center(deleted, center_id, person_id) values (false, 2, 28);
insert into administrator_center(deleted, center_id, person_id) values (false, 3, 29);
insert into administrator_center(deleted, center_id, person_id) values (false, 14, 30);
insert into administrator_center(deleted, center_id, person_id) values (false, 15, 31);
insert into administrator_center(deleted, center_id, person_id) values (false, 22, 32);
insert into administrator_center(deleted, center_id, person_id) values (false, 35, 33);
insert into administrator_center(deleted, center_id, person_id) values (false, 7, 34);
insert into administrator_center(deleted, center_id, person_id) values (false, 17, 35);